{
  "formatVersion": "1.1",
  "component": {
    "group": "aabric",
    "module": "stitch",
    "version": "0.6.2-aabric.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "icwn2jrdyfc3bgq2tghdtclqhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "stitch-0.6.2-aabric.3.jar",
          "url": "stitch-0.6.2-aabric.3.jar",
          "size": 160464,
          "sha512": "92efc61ae17623c1246d031c54e27585868cb771c03e077fa3805b5c20f05172cbdb42f6eff75bdfb88884f0c1538903c21829d5781b3ec5686aedfc888e8303",
          "sha256": "3c2fb298a573910553ee1b878cd92150d3e3fffed7588f3dc27e032cd4f41522",
          "sha1": "6884d3ef63ec844eb2b90fed2c52324e4f80abf3",
          "md5": "209d44a18a16872e0ad909cbfdb0f981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.3.0+build.17"
          }
        }
      ],
      "files": [
        {
          "name": "stitch-0.6.2-aabric.3.jar",
          "url": "stitch-0.6.2-aabric.3.jar",
          "size": 160464,
          "sha512": "92efc61ae17623c1246d031c54e27585868cb771c03e077fa3805b5c20f05172cbdb42f6eff75bdfb88884f0c1538903c21829d5781b3ec5686aedfc888e8303",
          "sha256": "3c2fb298a573910553ee1b878cd92150d3e3fffed7588f3dc27e032cd4f41522",
          "sha1": "6884d3ef63ec844eb2b90fed2c52324e4f80abf3",
          "md5": "209d44a18a16872e0ad909cbfdb0f981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stitch-0.6.2-aabric.3-sources.jar",
          "url": "stitch-0.6.2-aabric.3-sources.jar",
          "size": 81109,
          "sha512": "d8e4082bc6a4604bcc62e2f428ecdce3949779763949e301fbc4ce166672f4ec2e937ac353a8b156b690721e957a06ecd1f0d4d1809abbd34e2e3316dc65af6a",
          "sha256": "223db9156837a725827b2323383ba09d0a1095ff6013630145f1f0c1e1c25f3e",
          "sha1": "48ffc3d0a326fe79281dd200a72c3c52f7a5f7f4",
          "md5": "94fde10dbb288ab9b727c5ade50d43ac"
        }
      ]
    }
  ]
}
